# Generated by Django 4.2.7 on 2024-01-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0011_user_enable_reminders"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
