# Generated by Django 5.0.6 on 2024-05-18 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diary", "0012_user_last_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="created_date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="message",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="enable_reminders",
            field=models.BooleanField(default=True),
        ),
    ]
